export const SECTORS=['Sector A','Sector B','Sector C','Sector D'];
export const SKILLS=['Track','Electrical','Signals'];
export const time=n=>`${String(Math.floor(n/4)).padStart(2,'0')}:${String((n%4)*15).padStart(2,'0')}`;
export const active=j=>j.start!==null&&j.teamId&& !['submitted','deferred'].includes(j.status);
export const fixed=j=>j.locked||['acknowledged','in_progress','completed'].includes(j.status);
export const end=j=>j.start+j.setup+j.duration+j.clearance;
export const overlap=(a,b)=>a.start<end(b)&&b.start<end(a);
export function resources(state,date){return state.teams.map(t=>{const members=state.profiles.filter(p=>p.teamId===t.id);return {...t,start:Math.max(t.start,...members.map(p=>p.start)),end:Math.min(t.end,...members.map(p=>p.end)),unavailable:state.absences.some(a=>a.teamId===t.id&&a.date===date)||members.some(p=>p.unavailableDates.includes(date)),preferences:members.map(p=>p.preferred)};});}
export function pairReasons(a,b){if(a.date!==b.date||!overlap(a,b))return [];const r=[];if(a.sector===b.sector)r.push('Overlapping track access');if(a.teamId===b.teamId)r.push('Team double-booked');if(a.zone===b.zone&&[a.kind,b.kind].includes('isolation')&&[a.kind,b.kind].includes('live'))r.push('Live testing during power isolation');return r;}
export function validate(jobs,state,date){const list=jobs.filter(j=>j.date===date&&active(j)),res=resources(state,date),issues=[];for(let i=0;i<list.length;i++){const j=list[i],t=res.find(t=>t.id===j.teamId);const push=reason=>issues.push({jobIds:[j.id],reason});if(!t)push('Assigned team does not exist');else{if(t.skill!==j.skill)push('Team lacks required qualification');if(t.unavailable)push('Assigned team unavailable');if(j.start<t.start||end(j)>t.end||j.start<0||end(j)>24)push('Work, setup or clearance extends outside availability');}if(!j.ready)push('Equipment or access readiness is unconfirmed');if(j.dependsOn){const d=list.find(x=>x.id===j.dependsOn);if(!d||end(d)>j.start)push('Preceding job must finish before this job starts');}for(const b of list.slice(i+1))for(const reason of pairReasons(j,b))issues.push({jobIds:[j.id,b.id],reason});}return issues;}
function canPlace(j,placed,state,res){const t=res.find(t=>t.id===j.teamId);if(!t||t.unavailable||!j.ready||j.skill!==t.skill||j.start<t.start||end(j)>t.end||end(j)>24)return false;if(placed.some(b=>pairReasons(j,b).length))return false;if(j.dependsOn){const d=placed.find(b=>b.id===j.dependsOn);if(!d||end(d)>j.start)return false;}return true;}
export function propose(state,date,policy='stable'){
 const source=state.jobs.filter(j=>j.date===date),res=resources(state,date),pinned=source.filter(j=>active(j)&&fixed(j));
 // Dependencies are checked again after all placements, so a pinned successor can retain a movable predecessor.
 const pinIssues=validate(pinned.map(j=>({...j,dependsOn:null})),state,date);if(pinIssues.length)return {policy,blocked:true,issues:pinIssues,assignments:[],deferred:[],changes:[],metrics:{}};
 let pending=source.filter(j=>!pinned.some(p=>p.id===j.id)),ordered=[];while(pending.length){let available=pending.filter(j=>!j.dependsOn||!pending.some(p=>p.id===j.dependsOn));if(!available.length)available=pending.slice(0,1);available.sort((a,b)=>({urgent:0,high:1,routine:2}[a.priority]-{urgent:0,high:1,routine:2}[b.priority])||a.id.localeCompare(b.id));const n=available[0];ordered.push(n);pending=pending.filter(j=>j.id!==n.id);}
 let beam=[{placed:pinned.map(j=>({...j})),deferred:[],score:0}];
 for(const j of ordered){const next=[];for(const node of beam){const candidates=[];if(j.ready)for(const t of res.filter(t=>t.skill===j.skill&&!t.unavailable))for(let s=t.start;s+j.setup+j.duration+j.clearance<=Math.min(t.end,24);s++){const c={...j,start:s,teamId:t.id,status:'scheduled',acknowledgedBy:[]};if(canPlace(c,node.placed,state,res)&&!node.placed.some(p=>p.dependsOn===c.id&&end(c)>p.start)){const preferred=t.preferences.reduce((sum,p)=>sum+Math.abs(s-p),0);const movement=(j.start===null?0:Math.abs(s-j.start)*2)+(j.teamId&&t.id!==j.teamId?8:0);candidates.push({c,cost:policy==='stable'?movement*5+preferred+s*.01:s*3+preferred+movement*.1});}}
 candidates.sort((a,b)=>a.cost-b.cost);for(const {c,cost} of candidates.slice(0,30))next.push({placed:[...node.placed,c],deferred:node.deferred,score:node.score+cost});next.push({placed:node.placed,deferred:[...node.deferred,j],score:node.score+({urgent:1000000,high:100000,routine:10000}[j.priority])});}next.sort((a,b)=>a.score-b.score);beam=next.slice(0,50);}
 const valid=beam.filter(n=>!validate(n.placed,state,date).length);if(!valid.length)return {policy,blocked:true,issues:[{jobIds:[],reason:'No plan found that preserves locked work and job dependencies. Review locked jobs or availability.'}],assignments:[],deferred:[],changes:[],metrics:{}};const best=valid[0];const assignments=best.placed.map(j=>({id:j.id,start:j.start,teamId:j.teamId}));const deferred=best.deferred.map(j=>({id:j.id,reason:!j.ready?'Equipment / access not marked ready':j.dependsOn&&!best.placed.some(p=>p.id===j.dependsOn)?'Preceding job is not scheduled':'No compatible slot selected within crew, sector and six-hour window constraints; bounded search does not prove impossibility.'}));
 const changes=best.placed.filter(j=>{const old=source.find(o=>o.id===j.id);return old.start!==j.start||old.teamId!==j.teamId||!active(old)}).map(j=>{const old=source.find(o=>o.id===j.id);const causes=validate(source,state,date).filter(c=>c.jobIds.includes(j.id)).map(c=>c.reason);return {id:j.id,title:j.title,from:old.start===null?'Unscheduled':`${time(old.start)} · ${old.teamId||'unassigned'}`,to:`${time(j.start)} · ${j.teamId}`,reason:causes.length?[...new Set(causes)].join('; '):policy==='stable'?'Feasible slot with preference for preserving existing assignments':'Earlier feasible placement, considering worker preferences'};});
 return {policy,blocked:false,assignments,deferred,changes,metrics:{scheduled:assignments.length,urgent:best.placed.filter(j=>j.priority==='urgent').length,changed:changes.length,deferred:deferred.length,finish:best.placed.length?time(Math.max(...best.placed.map(end))):'—',conflicts:0},search:'Bounded beam search; feasible plan, not a proven global optimum'};
}
