import http from 'node:http';
import {Worker} from 'node:worker_threads';
import {FILES,loadDataset,describe,exportsFor,validatePlan} from './ps1.mjs';
import {DatabaseSync} from 'node:sqlite';
import {randomBytes,randomUUID,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {readFileSync,mkdirSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {SECTORS,SKILLS,validate,propose,active,fixed,end,time,resources} from './scheduler.mjs';
import {callAI,chatSystem} from './ai.mjs';
const base=path.dirname(fileURLToPath(import.meta.url));
const fail=(status,message)=>{throw Object.assign(new Error(message),{status})};
const text=(v,name,max=200)=>{if(typeof v!=='string'||!v.trim()||v.length>max)fail(400,`${name} is required (up to ${max} characters).`);return v.trim()};
const number=(v,name,min,max)=>{if(!Number.isInteger(v)||v<min||v>max)fail(400,`${name} must be an integer between ${min} and ${max}.`);return v};
const choice=(v,values,name)=>{if(!values.includes(v))fail(400,`Invalid ${name}.`);return v};
const date=v=>{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)fail(400,'Use a valid date.');return v};
const digest=s=>createHash('sha256').update(s).digest('hex');
const hash=p=>{const salt=randomBytes(16).toString('hex');return salt+':'+scryptSync(p,salt,64).toString('hex')};
function verify(p,h){const [salt,key]=h.split(':');return timingSafeEqual(scryptSync(p,salt,64),Buffer.from(key,'hex'))}
const publicUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role,teamId:u.team_id});
function initial(){return {version:1,jobs:[],teams:[{id:'Alpha',skill:'Track',start:0,end:24},{id:'Bravo',skill:'Electrical',start:0,end:24},{id:'Charlie',skill:'Track',start:0,end:24},{id:'Delta',skill:'Signals',start:0,end:24}],profiles:[],absences:[],events:[],notifications:[]};}
export function createApp({dbPath=process.env.RAILSYNC_DB||path.join(base,'data','railsync.sqlite'),fetcher=fetch}={}){
 if(dbPath!==':memory:')mkdirSync(path.dirname(dbPath),{recursive:true});const db=new DatabaseSync(dbPath);db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
 CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL,team_id TEXT);
 CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),csrf TEXT,expires INTEGER);
 CREATE TABLE IF NOT EXISTS ps1_workspace(id INTEGER PRIMARY KEY CHECK(id=1),body TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS workspace(id INTEGER PRIMARY KEY CHECK(id=1),body TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS proposals(id TEXT PRIMARY KEY,version INTEGER,body TEXT,created INTEGER);
 CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT,role TEXT,content TEXT,created TEXT);`);
 db.prepare('INSERT OR IGNORE INTO workspace VALUES(1,?)').run(JSON.stringify(initial()));
 const psGet=()=>{const row=db.prepare('SELECT body FROM ps1_workspace WHERE id=1').get();return row?JSON.parse(row.body):{version:0,files:null,results:{}}};
 const psSave=s=>db.prepare('INSERT INTO ps1_workspace VALUES(1,?) ON CONFLICT(id) DO UPDATE SET body=excluded.body').run(JSON.stringify(s));
 const psView=s=>({version:s.version,source:s.source,summary:s.files?describe(loadDataset(s.files)):null,results:s.results});
 let psBusy=false;
 const get=()=>JSON.parse(db.prepare('SELECT body FROM workspace WHERE id=1').get().body);
 const save=s=>{s.version++;db.prepare('UPDATE workspace SET body=? WHERE id=1').run(JSON.stringify(s))};
 const audit=(s,u,action,jobId,detail)=>s.events.push({id:randomUUID(),at:new Date().toISOString(),actor:u.name,actorId:u.id,action,jobId,detail});
 const notify=(s,u,job,message)=>{const ids=new Set([job.createdBy,...db.prepare("SELECT id FROM users WHERE role='scheduler'").all().map(u=>u.id),...db.prepare("SELECT id FROM users WHERE role='engineer' AND team_id=?").all(job.teamId||'').map(u=>u.id)]);for(const userId of ids)if(userId&&userId!==u.id)s.notifications.push({id:randomUUID(),userId,jobId:job.id,message,read:false,at:new Date().toISOString()});};
 const visible=(s,u)=>u.role==='scheduler'?s.jobs:s.jobs.filter(j=>u.role==='requester'?j.createdBy===u.id:j.teamId===u.team_id&&active(j));
 const view=(s,u,d)=>{const jobs=visible(s,u),ids=new Set(jobs.map(j=>j.id));return {version:s.version,jobs,teams:u.role==='engineer'?resources(s,d).filter(t=>t.id===u.team_id):resources(s,d),profile:s.profiles.find(p=>p.userId===u.id),users:u.role==='scheduler'?db.prepare('SELECT * FROM users').all().map(publicUser):[],profiles:u.role==='scheduler'?s.profiles:[],absences:u.role==='scheduler'?s.absences:[],events:s.events.filter(e=>u.role==='scheduler'||e.actorId===u.id||ids.has(e.jobId)).slice(-100).reverse(),notifications:s.notifications.filter(n=>n.userId===u.id).slice(-80).reverse(),conflicts:u.role==='scheduler'?validate(s.jobs,s,d):validate(s.jobs,s,d).filter(c=>c.jobIds.some(id=>ids.has(id))).map(c=>({...c,jobIds:c.jobIds.filter(id=>ids.has(id))})),ai:{configured:!!config.key,provider:config.provider,model:config.model,verified:config.verified},user:publicUser(u)};};
 let config={provider:process.env.ANTHROPIC_API_KEY&&!process.env.OPENAI_API_KEY?'anthropic':'openai',key:process.env.OPENAI_API_KEY||process.env.ANTHROPIC_API_KEY||'',model:process.env.RAILSYNC_MODEL||(process.env.ANTHROPIC_API_KEY&&!process.env.OPENAI_API_KEY?'claude-sonnet-4-6':'gpt-4.1-mini'),verified:false};
 const attempts=new Map(),aiBusy=new Set(),aiLimits=new Map();
 function limit(key,max,ms){const now=Date.now(),l=attempts.get(key)||{n:0,until:now+ms};if(l.until<now){l.n=0;l.until=now+ms}if(++l.n>max)fail(429,'Too many attempts. Try again shortly.');attempts.set(key,l)}
 function userCreate(b,s){const name=text(b.name,'Name',80),email=text(b.email,'Email',150).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))fail(400,'Enter a valid email address.');const password=text(b.password,'Password',200);if(password.length<12)fail(400,'Use a password with at least 12 characters.');choice(b.role,['scheduler','requester','engineer'],'role');if(b.role==='engineer'&&!s.teams.some(t=>t.id===b.teamId))fail(400,'Choose a team for this engineer.');if(db.prepare('SELECT id FROM users WHERE email=?').get(email))fail(409,'An account with this email already exists.');const u={id:randomUUID(),name,email,password:hash(password),role:b.role,team_id:b.role==='engineer'?b.teamId:null};db.prepare('INSERT INTO users VALUES(?,?,?,?,?,?)').run(u.id,name,email,u.password,u.role,u.team_id);s.profiles.push({userId:u.id,teamId:u.team_id,start:0,end:24,preferred:0,unavailableDates:[]});return u;}
 function login(u,res){const token=randomBytes(32).toString('hex'),csrf=randomBytes(24).toString('hex');db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(digest(token),u.id,csrf,Date.now()+8*3600000);res.setHeader('Set-Cookie',`railsync_${server.address().port}=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800`);return {user:publicUser(u),csrf};}
 const server=http.createServer(async(req,res)=>{
 res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Cache-Control','no-store');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");
 const send=(status,obj)=>{res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(obj))};
 try{
 const host=req.headers.host||'';if(!/^(127\.0\.0\.1|localhost)(:\d+)?$/.test(host))fail(403,'Localhost access only.');const url=new URL(req.url,'http://'+host),route=url.pathname;
 if(!route.startsWith('/api/')){const files={'/':'index.html','/app.js':'app.js','/style.css':'style.css','/ps1-ui.js':'ps1-ui.js'};if(!files[route])fail(404,'Not found');res.setHeader('Content-Type',route.endsWith('.js')?'text/javascript':route.endsWith('.css')?'text/css':'text/html');res.end(readFileSync(path.join(base,'public',files[route])));return;}
 if(req.method==='GET'&&route==='/api/health'){send(200,{ok:true,setupRequired:!db.prepare('SELECT id FROM users LIMIT 1').get()});return;}
 let b={};if(req.method!=='GET'){if(req.headers.origin&&req.headers.origin!=='http://'+host)fail(403,'Request origin rejected.');if(!String(req.headers['content-type']).startsWith('application/json'))fail(415,'JSON required.');let raw='';for await(const chunk of req){raw+=chunk;if(Buffer.byteLength(raw)>(route.startsWith('/api/ps1/')?8500000:40000))fail(413,'Request too large.');}try{b=JSON.parse(raw||'{}')}catch{fail(400,'Invalid JSON.')}if(!b||Array.isArray(b)||typeof b!=='object')fail(400,'JSON object required.');}
 if(req.method==='POST'&&route==='/api/setup'){if(db.prepare('SELECT id FROM users LIMIT 1').get())fail(409,'Workspace already initialized. Sign in.');const s=get(),u=userCreate({...b,role:'scheduler'},s);audit(s,u,'Workspace created',null,'Local scheduler account created.');save(s);send(201,login(u,res));return;}
 if(req.method==='POST'&&route==='/api/login'){limit('login:'+req.socket.remoteAddress,30,60000);const email=text(b.email,'Email',150).toLowerCase(),password=text(b.password,'Password',200),u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!u||!verify(password,u.password))fail(401,'Email or password is incorrect.');send(200,login(u,res));return;}
 const cookieName='railsync_'+server.address().port+'='; const token=(req.headers.cookie||'').split('; ').find(x=>x.startsWith(cookieName))?.slice(cookieName.length);const session=token&&db.prepare('SELECT * FROM sessions WHERE token=? AND expires>?').get(digest(token),Date.now());if(!session)fail(401,'Please sign in.');const u=db.prepare('SELECT * FROM users WHERE id=?').get(session.user_id);if(req.method!=='GET'&&req.headers['x-csrf-token']!==session.csrf)fail(403,'Session verification failed. Refresh and retry.');const scheduler=()=>{if(u.role!=='scheduler')fail(403,'Only a scheduler can perform this action.')};
 if(route.startsWith('/api/ps1/')){
 scheduler();
 if(route==='/api/ps1/state'&&req.method==='GET'){send(200,psView(psGet()));return;}
 if(route==='/api/ps1/import'&&req.method==='POST'){
 const previous=psGet();if(b.version!==previous.version)fail(409,'The PS1 dataset changed. Refresh the planner.');
 let files;if(b.sample)files=Object.fromEntries(FILES.map(f=>[f,readFileSync(path.join(base,'ps1-reference','01_data',f),'utf8')]));else{if(!b.files||typeof b.files!=='object'||Array.isArray(b.files)||Object.keys(b.files).length!==8)fail(400,'Upload exactly the eight named instance CSV files.');files=Object.fromEntries(FILES.map(f=>[f,b.files[f]]));}
 try{loadDataset(files);}catch(e){fail(400,e.message);}
 const next={version:previous.version+1,source:b.sample?'NebulaX public PS1 dataset · 16526c0':'Uploaded instance',files,results:{}};psSave(next);const s=get();audit(s,u,'PS1 dataset imported',null,next.source);save(s);send(200,psView(next));return;
 }
 if(route==='/api/ps1/solve'&&req.method==='POST'){
 const snapshot=psGet();if(!snapshot.files)fail(400,'Load the sample or upload eight CSV files first.');if(b.version!==snapshot.version)fail(409,'The dataset changed. Refresh the planner.');choice(b.scenario,['A','B','C'],'scenario');if(psBusy)fail(409,'A PS1 solve is already running.');psBusy=true;
 try{const result=await new Promise((resolve,reject)=>{const worker=new Worker(new URL('./ps1-worker.mjs',import.meta.url),{workerData:{files:snapshot.files,scenario:b.scenario}});const timeout=setTimeout(()=>{worker.terminate();reject(Object.assign(Error('Planning reached the 60-second limit. The previous saved result is unchanged.'),{status:422}));},60000);worker.once('message',message=>{clearTimeout(timeout);message.error?reject(Object.assign(Error(message.error),{status:422})):resolve(message.result);});worker.once('error',e=>{clearTimeout(timeout);reject(e)});worker.once('exit',code=>{clearTimeout(timeout);if(code!==0)reject(Error('Solver worker stopped unexpectedly.'));});});
 const latest=psGet();if(latest.version!==snapshot.version)fail(409,'Dataset changed during planning. Discarded the stale result.');latest.results[b.scenario]=result;psSave(latest);const s=get();audit(s,u,'PS1 scenario generated',null,b.scenario+': '+result.report.complete_activities+'/'+result.report.total_activities+' activities; '+result.report.hard_violations.length+' internal rule violations.');save(s);send(200,result);
 }finally{psBusy=false;}return;
 }
 if(route==='/api/ps1/export'&&req.method==='GET'){
 const scenario=url.searchParams.get('scenario'),filename=url.searchParams.get('file');choice(scenario,['A','B','C'],'scenario');choice(filename,['SCHEDULE_ACCESS.csv','SCHEDULE_OCCUPANCY.csv','RESULTS.csv','VALIDATION.json'],'file');const s=psGet(),result=s.results[scenario];if(!result)fail(404,'Generate this scenario first.');const report=validatePlan(loadDataset(s.files),scenario,result.access,result.occupancy);if(filename!=='VALIDATION.json'&&!report.feasible)fail(422,'This candidate has hard violations. Download its validation report and resolve the input or planning constraints before exporting a submission.');res.setHeader('Content-Type',filename.endsWith('.csv')?'text/csv; charset=utf-8':'application/json');res.setHeader('Content-Disposition','attachment; filename="'+filename+'"');res.end(filename==='VALIDATION.json'?JSON.stringify(report,null,2):exportsFor({...result,report})[filename]);return;
 }
 fail(404,'Unknown PS1 action');
 }
 if(route==='/api/me'&&req.method==='GET'){send(200,{user:publicUser(u),csrf:session.csrf});return;}
 if(route==='/api/logout'&&req.method==='POST'){db.prepare('DELETE FROM sessions WHERE token=?').run(session.token);res.setHeader('Set-Cookie','railsync_'+server.address().port+'=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');send(200,{ok:true});return;}
 if(route==='/api/state'&&req.method==='GET'){send(200,view(get(),u,date(url.searchParams.get('date'))));return;}
 if(route==='/api/chat/history'&&req.method==='GET'){send(200,db.prepare('SELECT role,content,created FROM messages WHERE user_id=? ORDER BY id DESC LIMIT 30').all(u.id).reverse());return;}
 if(route==='/api/ai/config'&&req.method==='POST'){scheduler();if(b.disconnect){config={...config,key:'',verified:false};send(200,{ok:true});return;}choice(b.provider,['openai','anthropic'],'provider');const model=text(b.model,'Model',100);if(!/^[a-zA-Z0-9._:-]+$/.test(model))fail(400,'Invalid model identifier.');const key=b.key?text(b.key,'API key',500):config.provider===b.provider?config.key:'';if(!key)fail(400,'Enter an API key.');config={provider:b.provider,model,key,verified:false};send(200,{ok:true});return;}
 if(route==='/api/ai/test'&&req.method==='POST'){scheduler();limit('test:'+u.id,5,60000);const current=config;await callAI(current,[{role:'user',content:'Reply with: Connected'}],'You are testing an API connection. Reply briefly.',fetcher);if(current===config)config.verified=true;send(200,{ok:true,provider:current.provider,model:current.model});return;}
 if((route==='/api/chat'||route==='/api/ai/draft')&&req.method==='POST'){
 const prompt=text(b.message,'Message',4000);if(route.endsWith('draft')&&u.role==='engineer')fail(403,'Only requesters and schedulers can draft requests.');if(!config.key)fail(503,'AI is not connected. The scheduler can connect an API key in Settings.');limit('chat:'+u.id,12,60000);if(aiBusy.has(u.id))fail(429,'Wait for your current AI response.');aiBusy.add(u.id);try{const snapshot=view(get(),u,date(b.date));const context={date:b.date,role:u.role,jobs:snapshot.jobs.filter(j=>j.date===b.date).map(({notes,...j})=>j),teams:snapshot.teams,conflicts:snapshot.conflicts};if(u.role==='scheduler'){const ps=psGet();if(ps.files)context.ps1={dataset:describe(loadDataset(ps.files)),scenarios:Object.fromEntries(Object.entries(ps.results).map(([k,r])=>[k,{report:r.report,activities:r.explanations}]))};}let system=chatSystem+'\nAUTHORIZED DATA:\n'+JSON.stringify(context);let messages=[{role:'user',content:prompt}];if(route==='/api/chat'){const history=db.prepare('SELECT role,content FROM messages WHERE user_id=? ORDER BY id DESC LIMIT 8').all(u.id).reverse();messages=[...history,...messages];}else system+='\nExtract a request as JSON ONLY: {"title":string,"sector":"Sector A"|"Sector B"|"Sector C"|"Sector D"|null,"skill":"Track"|"Electrical"|"Signals"|null,"durationMinutes":number|null,"priority":"routine"|"high"|"urgent"|null,"kind":"inspection"|"repair"|"isolation"|"live"|null,"notes":string,"missing":string[]}. Do not guess missing location, qualification or duration. This is a draft requiring user review.';const reply=await callAI(config,messages,system,fetcher);if(route.endsWith('draft')){let draft;try{draft=JSON.parse(reply.replace(/^```(?:json)?\s*/,'').replace(/\s*```$/,''));if(!draft||typeof draft!=='object'||Array.isArray(draft))throw Error();}catch{fail(502,'The AI did not return a valid draft. Try again or use the request form.');}send(200,{draft});}else{const at=new Date().toISOString(),insert=db.prepare('INSERT INTO messages(user_id,role,content,created) VALUES(?,?,?,?)');insert.run(u.id,'user',prompt,at);insert.run(u.id,'assistant',reply,at);send(200,{reply});}}finally{aiBusy.delete(u.id);}return;}
 if(req.method!=='POST')fail(404,'Not found');const s=get();if(b.version!==s.version)fail(409,'The workspace changed. Refresh, review the latest plan, and try again.');
 if(route==='/api/users'){scheduler();const created=userCreate(b,s);audit(s,u,'Account created',null,`${created.name} · ${created.role}`);save(s);send(201,{user:publicUser(created)});return;}
 if(route==='/api/profile'){const p=s.profiles.find(p=>p.userId===u.id);const start=number(b.start,'Start',0,23),finish=number(b.end,'End',1,24);if(start>=finish)fail(400,'End must be later than start.');p.preferred=number(b.preferred,'Preferred start',start,finish-1);if(u.role==='engineer'){// A worker may narrow availability, but only a scheduler can expand approved team hours.
 const team=s.teams.find(t=>t.id===u.team_id);if(start<team.start||finish>team.end)fail(400,'Availability must be within approved team hours.');}p.start=start;p.end=finish;if(!Array.isArray(b.unavailableDates)||b.unavailableDates.length>60)fail(400,'Maximum 60 unavailable dates.');p.unavailableDates=[...new Set(b.unavailableDates.map(date))];audit(s,u,'Profile updated',null,'Availability and preferred start updated. Existing bookings require review if affected.');save(s);send(200,{ok:true});return;}
 if(route==='/api/absence'){scheduler();const t=s.teams.find(t=>t.id===b.teamId);if(!t)fail(400,'Unknown team.');const d=date(b.date);s.absences=s.absences.filter(a=>!(a.teamId===t.id&&a.date===d));if(b.unavailable)s.absences.push({teamId:t.id,date:d});audit(s,u,'Team availability changed',null,`${t.id} · ${d} · ${b.unavailable?'unavailable':'available'}`);save(s);send(200,{ok:true});return;}
 if(route==='/api/seed'){scheduler();const d=date(b.date);if(s.jobs.some(j=>j.date===d))fail(409,'Sample requests can only be added to an empty date.');const samples=[['Rail surface inspection','Sector A','Track',1,4,'Alpha','urgent','inspection'],['Track geometry check','Sector A','Track',3,3,'Charlie','routine','inspection'],['Switch servicing','Sector B','Track',3,3,'Alpha','routine','repair'],['Power isolation','Sector C','Electrical',2,4,'Bravo','urgent','isolation'],['Live signal testing','Sector D','Signals',4,3,'Delta','routine','live'],['Fastener replacement','Sector B','Track',10,3,'Charlie','high','repair']];for(const [title,sector,skill,start,duration,teamId,priority,kind]of samples)s.jobs.push({id:randomUUID(),title,date:d,sector,skill,start,duration,setup:0,clearance:0,teamId,priority,kind,zone:'Shared zone',ready:true,status:'scheduled',locked:false,createdBy:u.id,notes:'Illustrative sample request',dependsOn:null,acknowledgedBy:[],deferrals:0});audit(s,u,'Sample requests loaded',null,`Six illustrative requests for ${d}.`);save(s);send(201,{ok:true});return;}
 if(route==='/api/jobs'){if(!['requester','scheduler'].includes(u.role))fail(403,'Only requesters and schedulers can submit work.');const d=date(b.date);if(s.jobs.filter(j=>j.date===d).length>=35)fail(400,'This local planner supports up to 35 requests per date.');const j={id:randomUUID(),title:text(b.title,'Title',140),date:d,sector:choice(b.sector,SECTORS,'sector'),skill:choice(b.skill,SKILLS,'qualification'),priority:choice(b.priority,['urgent','high','routine'],'priority'),kind:choice(b.kind,['inspection','repair','isolation','live'],'work type'),zone:text(b.zone||'Shared zone','Electrical zone',60),duration:number(b.duration,'Duration',1,20),setup:number(b.setup,'Setup',0,8),clearance:number(b.clearance,'Clearance',0,8),ready:b.ready===true,notes:typeof b.notes==='string'?b.notes.slice(0,2000):'',dependsOn:b.dependsOn||null,start:null,teamId:null,status:'submitted',locked:false,createdBy:u.id,acknowledgedBy:[],deferrals:0};if(j.dependsOn&&!s.jobs.some(x=>x.id===j.dependsOn&&x.date===d&&visible(s,u).some(y=>y.id===x.id)))fail(400,'Select an accessible preceding job on the same date.');s.jobs.push(j);audit(s,u,'Request submitted',j.id,j.title);save(s);send(201,{job:j});return;}
 if(route==='/api/job/action'){const j=s.jobs.find(j=>j.id===b.id);if(!j)fail(404,'Request not found.');if(u.role!=='scheduler'&&!visible(s,u).some(x=>x.id===j.id))fail(403,'You cannot update this request.');const action=choice(b.action,['ready','lock','acknowledge','start','complete','delay','reopen'],'action');
 if(action==='ready'){if(u.role==='engineer')fail(403,'Readiness must be confirmed by a requester or scheduler.');j.ready=b.value===true;}
 if(action==='lock'){scheduler();if(!active(j)||['in_progress','completed'].includes(j.status))fail(400,'Only scheduled or acknowledged work can be locked or unlocked.');j.locked=b.value===true;if(!j.locked&&j.status==='acknowledged'){j.status='scheduled';j.acknowledgedBy=[];}}
 if(['acknowledge','start','complete','delay'].includes(action)){if(u.role!=='engineer'||u.team_id!==j.teamId)fail(403,'This action belongs to an engineer on the assigned team.');if(action==='acknowledge'){if(j.status!=='scheduled')fail(400,'Only scheduled work can be acknowledged.');j.status='acknowledged';j.acknowledgedBy=[u.id];}if(action==='start'){if(j.status!=='acknowledged')fail(400,'Acknowledge the assignment first.');if(validate(s.jobs,s,j.date).some(c=>c.jobIds.includes(j.id)))fail(409,'Resolve this job’s scheduling conflicts before starting.');j.status='in_progress';}if(action==='complete'){if(j.status!=='in_progress')fail(400,'Start the job before completing it.');j.status='completed';j.completedAt=new Date().toISOString();}if(action==='delay'){if(!['acknowledged','in_progress'].includes(j.status))fail(400,'Only acknowledged or active work can report a delay.');j.duration+=number(b.extra,'Additional duration',1,8);j.delayReason=text(b.reason,'Delay reason',500);}}
 if(action==='reopen'){scheduler();if(j.status!=='deferred')fail(400,'Only deferred work can be carried forward.');const next=date(b.date);if(next<=j.date)fail(400,'Choose a later maintenance date.');const predecessor=s.jobs.find(x=>x.id===j.dependsOn);if(predecessor&&predecessor.status!=='completed')fail(400,'Carry forward or complete the preceding job first.');if(s.jobs.some(x=>x.dependsOn===j.id&&x.status!=='completed'))fail(400,'This request has dependants. Resolve their dependency before moving it to another date.');j.date=next;j.dependsOn=null;j.status='submitted';j.start=null;j.teamId=null;j.locked=false;}
 audit(s,u,'Job '+action,j.id,action==='delay'?`Additional ${b.extra*15} minutes: ${j.delayReason}`:j.title);notify(s,u,j,`${j.title}: ${action==='delay'?'delay reported; plan needs review':action}`);save(s);send(200,{ok:true});return;}
 if(route==='/api/proposals'){scheduler();const d=date(b.date);if(!s.jobs.some(j=>j.date===d))fail(400,'Add at least one request first.');const plans=['stable','early'].map(policy=>({...propose(s,d,policy),id:randomUUID(),date:d,version:s.version}));const stmt=db.prepare('INSERT INTO proposals VALUES(?,?,?,?)');db.prepare('DELETE FROM proposals WHERE created<?').run(Date.now()-86400000);for(const p of plans)stmt.run(p.id,s.version,JSON.stringify(p),Date.now());send(200,{plans});return;}
 if(route==='/api/approve'){scheduler();const row=db.prepare('SELECT * FROM proposals WHERE id=?').get(text(b.id,'Proposal ID'));if(!row)fail(404,'Proposal not found. Generate alternatives again.');if(row.version!==s.version)fail(409,'Proposal is stale. Generate alternatives from the current workspace.');const p=JSON.parse(row.body);if(p.blocked)fail(400,'A blocked proposal cannot be approved.');const before=structuredClone(s.jobs);for(const a of p.assignments){const j=s.jobs.find(j=>j.id===a.id);if(!fixed(j)){j.start=a.start;j.teamId=a.teamId;j.status='scheduled';j.acknowledgedBy=[];}}for(const d of p.deferred){const j=s.jobs.find(j=>j.id===d.id);if(fixed(j))fail(409,'Cannot defer locked work.');j.start=null;j.teamId=null;j.status='deferred';j.deferralReason=d.reason;j.deferrals++;}if(validate(s.jobs,s,p.date).length)fail(409,'The plan failed final constraint validation.');for(const j of s.jobs.filter(j=>j.date===p.date)){const old=before.find(o=>o.id===j.id);if(JSON.stringify(old)!==JSON.stringify(j)){audit(s,u,'Plan approved',j.id,`${j.title}: ${j.status==='deferred'?j.deferralReason:time(j.start)+' · '+j.teamId}`);notify(s,u,j,j.status==='deferred'?`${j.title} was deferred: ${j.deferralReason}`:`${j.title}: approved for ${time(j.start)} with ${j.teamId}. Acknowledgement needed.`);if(old.teamId&&old.teamId!==j.teamId)notify(s,u,{...j,teamId:old.teamId},`${j.title} reassigned from your team.`);}}save(s);send(200,{ok:true});return;}
 if(route==='/api/notifications/read'){s.notifications.filter(n=>n.userId===u.id).forEach(n=>n.read=true);save(s);send(200,{ok:true});return;}
 fail(404,'Not found');
 }catch(error){send(error.status||500,{error:error.status?error.message:'Unexpected server error. No action was confirmed.'});if(!error.status)console.error('Server error:',error.code||error.name);}
 });
 return {server,db,close:()=>new Promise(resolve=>server.close(()=>{db.close();resolve()}))};
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const app=createApp();const port=Number(process.env.PORT||3001);app.server.listen(port,'127.0.0.1',()=>console.log(`RailSync running at http://127.0.0.1:${port} — data persists in SQLite. Press Ctrl+C to stop.`));}
